name: Retrain Model

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        run: |
          git clone  https://github.com/Annmary777/Chest-Cancer-Detection-using-MLOps1.git 
 .
          git pull

      - name: Set up Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc[all] mlflow dagshub

      - name: Pull DVC data
        run: dvc pull

      - name: Check Incorrect Predictions Threshold
        id: check_threshold
        run: |
          python -c "
import json
with open('incorrect_predictions.json', 'r') as f:
    data = json.load(f)
if len(data) > 5:
    print('::set-output name=trigger_retrain::true')
else:
    print('::set-output name=trigger_retrain::false')
"
        shell: bash

      - name: Trigger Retraining
        if: steps.check_threshold.outputs.trigger_retrain == 'true'
        run: dvc repro feedback_retraining
