name: Retrain Model

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dvc[all] mlflow dagshub

      - name: Configure DVC remote
        run: |
          dvc remote modify origin --local auth basic
          dvc remote modify origin --local user ${{ secrets.DAGSHUB_USERNAME }}
          dvc remote modify origin --local password ${{ secrets.DAGSHUB_ACCESS_TOKEN }}

      - name: Pull DVC data
        run: dvc pull

      - name: Check Incorrect Predictions Threshold
        id: check_threshold
        run: |
          python -c "
import json
with open('incorrect_predictions.json', 'r') as f:
    data = json.load(f)
if len(data) > 5:
    with open('${GITHUB_ENV}', 'a') as env_file:
        env_file.write('TRIGGER_RETRAIN=true\n')
else:
    with open('${GITHUB_ENV}', 'a') as env_file:
        env_file.write('TRIGGER_RETRAIN=false\n')
"
        shell: bash

      - name: Trigger Retraining
        if: env.TRIGGER_RETRAIN == 'true'
        run: dvc repro feedback_retraining

      - name: Push Retrained Artifacts
        if: env.TRIGGER_RETRAIN == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Push retrained model and updated artifacts"
          git push
